# -*- mode: ruby -*-
# vi: set ft=ruby :
# To enable zsh, please set ENABLE_ZSH env var to "true" before launching vagrant up 
#   + On windows => $env:ENABLE_ZSH="true"
#   + On Linux  => export ENABLE_ZSH="true"

# Définition des variables
RAM = 2048
CPU = 2
IP = "192.168.99.20"
TYPE = "static"
NAME = "dockercentos"

Vagrant.configure("2") do |config|
  config.vm.define "dockercentos" do |dockercentos|
    dockercentos.vm.box = "geerlingguy/centos7"
    dockercentos.vm.network "private_network", type: TYPE, ip: IP
    dockercentos.vm.hostname = NAME
	
    dockercentos.vm.provider "virtualbox" do |v|
      v.name = NAME
      v.memory = RAM
      v.cpus = CPU
    end
	
    dockercentos.vm.provision :shell do |shell|
      shell.path = "install_dockercentos.sh"
      shell.env = { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
    end
  end
end